export const NOTIFICATION_ENTITY = {
  VEHICLE: 'VEHICLE',
  MAINTENANCE_ITEM: 'MAINTENANCE_ITEM',
  TASK: 'TASK',
  SYSTEM: 'SYSTEM',
} as const;

export const NOTIFICATION_EVENT = {
  SOAT_EXPIRY: 'SOAT_EXPIRY',
  TECH_INSPECTION_EXPIRY: 'TECH_INSPECTION_EXPIRY',
  MAINTENANCE_DUE: 'MAINTENANCE_DUE',
  TASK_DUE: 'TASK_DUE',
  HOUR_METER_DAILY: 'HOUR_METER_DAILY',
} as const;

export const VEHICLE_REQUIRED_EVENTS = [
  NOTIFICATION_EVENT.SOAT_EXPIRY,
  NOTIFICATION_EVENT.TECH_INSPECTION_EXPIRY,
] as const;
