ALTER TYPE "EmployeeRole" ADD VALUE IF NOT EXISTS 'HEAVY_MACHINERY_OPERATOR';
ALTER TYPE "EmployeeRole" ADD VALUE IF NOT EXISTS 'MACHINIST';
ALTER TYPE "EmployeeRole" ADD VALUE IF NOT EXISTS 'OFFICE';
ALTER TYPE "EmployeeRole" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "EmployeeRole" ADD VALUE IF NOT EXISTS 'OPERATIONS_MANAGER';
ALTER TYPE "EmployeeRole" ADD VALUE IF NOT EXISTS 'MECHANIC';
ALTER TYPE "EmployeeRole" ADD VALUE IF NOT EXISTS 'WAREHOUSE_KEEPER';
