ALTER TABLE "Asset"
  ADD COLUMN IF NOT EXISTS "year" INTEGER,
  ADD COLUMN IF NOT EXISTS "fuel" TEXT;

ALTER TABLE "Sku"
  DROP COLUMN IF EXISTS "brand",
  DROP COLUMN IF EXISTS "model",
  DROP COLUMN IF EXISTS "year",
  DROP COLUMN IF EXISTS "fuel";
