export const SKU_CATEGORIES = [
  'FORMALETA',
  'COMPACTADORES',
  'HERRAMIENTAS ELECTRICAS DE PERCUSION',
  'HERRAMIENTAS NEUMATICAS',
  'MAQUINARIA AMARILLA',
  'DEMOLICION',
  'ENCOFRADO',
  'ALTURAS',
  'ANDAMIOS',
  'SIN_CATEGORIA',
] as const;

export const SKU_WEIGHT_UNITS = ['KG', 'TON'] as const;
